# Generated by Django 4.2.1 on 2023-06-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_alter_record_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='client_first_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='client_last_name',
        ),
    ]
