# Generated by Django 4.2.1 on 2023-06-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_rename_first_name_record_client_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='country',
        ),
    ]
